---
services:
  retriever:
    build:
      context: .
      dockerfile: client/retriever/retriever.Dockerfile
    container_name: r3mobprod_retriever
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 250M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5001:5001"
        #volumes:
        #- ./config_crossref:/api-flask

  nginx_retriever:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    container_name: r3mobprod_nginx_retriever
    volumes:
      - ./nginx/conf.d/default_retriever.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/socket.io/index.html
    ports:
      - "5022:443"
    depends_on:
      - retriever
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 25M
    networks:
      - classification-net

  classifier:
    build:
      context: .
      dockerfile: client/classifier/classifier.Dockerfile
    container_name: r3mobprod_classifier
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 600M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5011:5011"
        #volumes:
        #- ./config_classifier:/api-flask

  nginx_classifier:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    container_name: r3mobprod_nginx_classifier
    volumes:
      - ./nginx/conf.d/default_classifier.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/socket.io/index.html
    ports:
      - "5023:443"
    depends_on:
      - classifier
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 25M
    networks:
      - classification-net

      #frontend_dev:
      #build:
      #context: .
      #dockerfile: frontend/frontend_dev.Dockerfile
      #container_name: r3mobdev_frontend
      #restart: unless-stopped
      #deploy:
      #resources:
      #limits:
      #cpus: '0.70'
      #memory: 200M
      #network_mode: "host"
      ##networks:
      ##- classification-net
      #environment:
      #- PUID=1000
      #- PGID=1000
      #ports:
      #- "5180:5180"
      ##volumes:
      ##- ./config_frontend_dev:/api

networks:
  classification-net:

