services:

  crossref:
    build:
      context: ./client/api/crossref
      dockerfile: crossref.Dockerfile
    container_name: r3mobprod_crossref
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "${CROSSREF_PORT}:5001"
    volumes:
      - ./config_crossref:/api-flask

  classifier:
    build:
      context: ./
      dockerfile: client/classifier/classifier.Dockerfile
    container_name: r3mobprod_classifier
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 1G
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "${CLASSIFIER_PORT}:5011"
    volumes:
      - ./config_classifier:/api-flask

networks:
  classification-net:

