---
services:
  retriever:
    build:
      context: .
      dockerfile: client/retriever/retriever.Dockerfile
    container_name: r3mobprod_retriever
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 250M
            #networks:
      #- classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5001:5001"
        #volumes:
        #- ./config_crossref:/api-flask

  classifier:
    build:
      context: .
      dockerfile: client/classifier/classifier.Dockerfile
    container_name: r3mobprod_classifier
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 600M
      #networks:
      #- classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5011:5011"
        #volumes:
        #- ./config_classifier:/api-flask

  frontend_dev:
    build:
      context: .
      dockerfile: frontend/frontend_dev.Dockerfile
    container_name: r3mobdev_frontend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 200M
    network_mode: "host"
      #networks:
      #- classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5180:5180"
        #volumes:
        #- ./config_frontend_dev:/api

networks:
  classification-net:

