---
services:
  retriever_1:
    build:
      context: .
      dockerfile: client/retriever/retriever.Dockerfile
    container_name: r3mobprod_retriever_1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 100M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5001:5001"
        #volumes:
        #- ./config_crossref:/api-flask

  retriever_2:
    build:
      context: .
      dockerfile: client/retriever/retriever.Dockerfile
    container_name: r3mobprod_retriever_2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 100M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5002:5001"
        #volumes:
        #- ./config_crossref:/api-flask

  nginx_retriever:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    container_name: r3mobprod_retriever_nginx
    volumes:
      - ./nginx/conf.d/default_retriever.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/socket.io/index.html
    ports:
      - "5022:443"
    depends_on:
      - retriever_1
      - retriever_2
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 25M
    networks:
      - classification-net

        #retriever_redis:
        #image: redis:alpine
        #container_name: r3mobprod_retriever_redis
        #logging:
        #driver: "json-file"
        #options:
        #max-size: "10m"
        #max-file: "3"
        #deploy:
        #resources:
        #limits:
        #cpus: '0.70'
        #memory: 100M
        #expose:
        #- "6379"
        #networks:
        #- classification-net

  classifier:
    build:
      context: .
      dockerfile: client/classifier/classifier.Dockerfile
    container_name: r3mobprod_classifier
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 600M
    networks:
      - classification-net
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5011:5011"
        #volumes:
        #- ./config_classifier:/api-flask

  nginx_classifier:
    build:
      context: nginx/
      dockerfile: nginx.Dockerfile
    container_name: r3mobprod_classifier_nginx
    volumes:
      - ./nginx/conf.d/default_classifier.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/socket.io/index.html
    ports:
      - "5023:443"
    depends_on:
      - classifier
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: 25M
    networks:
      - classification-net

      #frontend_dev:
      #build:
      #context: .
      #dockerfile: frontend/frontend_dev.Dockerfile
      #container_name: r3mobdev_frontend
      #restart: unless-stopped
      #deploy:
      #resources:
      #limits:
      #cpus: '0.70'
      #memory: 200M
      #network_mode: "host"
      ##networks:
      ##- classification-net
      #environment:
      #- PUID=1000
      #- PGID=1000
      #ports:
      #- "5180:5180"
      ##volumes:
      ##- ./config_frontend_dev:/api

networks:
  classification-net:

